dist: xenial
language: python

python:
  - "3.7"

sudo: false

git:
  depth: 99999

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt

script:
  - npm install -g serverless
  - ./scripts/code_check.sh

after_success:
  - codecov

before_deploy:
  - npm --version
  - npm install -g serverless

deploy:
  # Serverless deploy to dev environment after merging to master branch
  - provider: script
    script: ./script/deploy_manage_ec2.sh
    skip_cleanup: true  # Don't re-run the tests
    on:
      branch: feature/schedule-start-stop
