dist: xenial
language: python

python:
  - "3.7"

sudo: false

git:
  depth: 99999

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt

script:
  - npm install -g serverless
  - ./scripts/code_check.sh

after_success:
  - codecov

before_deploy:
  - npm --version

deploy:
  # Serverless deploy to dev environment after merging to production branch
  - provider: script
    script:
      - npm install -g serverless
      # Configure serverless AWS custom profile settings.
      # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION are expected to be
      # configured in travis project web settings
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile devProfile --overwrite
      - cd lambda_functions/manage_ec2/ && npm install
      - serverless deploy -v --stage dev
    skip_cleanup: true  # Don't re-run the tests
