name: Unit Test

on:
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/dea-dev-infra/lambda_functions
          python -m unittest lambda_functions/manage_ec2/test_handler.py
